// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXME3DlI2sK8dalT3A_pfCQOOY3ORu8Oc',
    appId: '1:794890630444:web:2a806c3462716b05936889',
    messagingSenderId: '794890630444',
    projectId: 'fullstacktrial-92e4d',
    authDomain: 'fullstacktrial-92e4d.firebaseapp.com',
    storageBucket: 'fullstacktrial-92e4d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEvYLMNQ30HMTS8AHVDFpTdb5Qto3OW7M',
    appId: '1:794890630444:ios:e11672601d8cc9a3936889',
    messagingSenderId: '794890630444',
    projectId: 'fullstacktrial-92e4d',
    storageBucket: 'fullstacktrial-92e4d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEvYLMNQ30HMTS8AHVDFpTdb5Qto3OW7M',
    appId: '1:794890630444:ios:e11672601d8cc9a3936889',
    messagingSenderId: '794890630444',
    projectId: 'fullstacktrial-92e4d',
    storageBucket: 'fullstacktrial-92e4d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgwy4XaQjnp8yB10PQOErx2RKSqyulnnA',
    appId: '1:794890630444:android:79088a58b088eed2936889',
    messagingSenderId: '794890630444',
    projectId: 'fullstacktrial-92e4d',
    storageBucket: 'fullstacktrial-92e4d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXME3DlI2sK8dalT3A_pfCQOOY3ORu8Oc',
    appId: '1:794890630444:web:5832c0ad26006623936889',
    messagingSenderId: '794890630444',
    projectId: 'fullstacktrial-92e4d',
    authDomain: 'fullstacktrial-92e4d.firebaseapp.com',
    storageBucket: 'fullstacktrial-92e4d.appspot.com',
  );

}